### ISSUE TITLE
Capture kernel version

### ISSUE THREAD

**Issue by nellicus** [elastic/elasticsearch-support-diagnostics#63] opened 2015-05-11 10:54 UTC
Linux
$ uname -a
Linux w530 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

OSX
$ uname -a
Darwin Antonios-MacBook-Air-2.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64

Windows
http://www.windows-commandline.com/find-windows-os-version-from-command/ ?

**Comment by nellicus** [comment] 2015-05-11 10:54
@jjfalling

**Comment by joshuar** [comment] 2015-05-11 23:10
For just the kernel version, probably `uname -r` is enough on Linux.  Not sure if that parameter works the same on OSX?

**Comment by jjfalling** [comment] 2015-09-29 14:03
Duplicate of https://github.com/elastic/elasticsearch-internal-support-tools/issues/55

**Comment by nemonster** [comment] 2016-01-13 20:38
Given that this will only identify the the host where the diagnostic is being run, it would seem to limit the usefulness as a first pass diagnostic.  Although it's easy enough to add, at least for Linux.

**Comment by jjfalling** [comment] 2016-01-16 21:03
I think the current version is sufficient. @joshuar @nellicus  thoughts?

**Closed** 2016-03-23 21:51 UTC
Labels: 2.1, enhancement
